language: cpp

matrix:
  # Linux x86_64
  include:
  - os: linux

    env:
    - TARGET_ARCHITECTURE=x86_64
    - TRAVIS_NODE_VERSION="7"

    compiler:
    - gcc

    install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - sudo apt-get install -y nodejs

    addons:
        apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - gcc-4.9
            - g++-4.9
            - cmake
            - libsqlite3-dev
            - curl
            - libcurl4-openssl-dev
            - libssl-dev
            - libudev-dev
            - git

    script:
    - cmake -DDEBUG=OFF . && make && cd www && npm install && npm build

  # OSX
  - os: osx
    osx_image: xcode6.2

    env:
    - TARGET_ARCHITECTURE=x86_64
    - TRAVIS_NODE_VERSION="7"

    compiler:
    - gcc

    install:
      - brew install libusb
      - brew install libusb-compat
      - brew install openssl
      - brew link openssl --force
      - brew install node
      - export OPENSSL_ROOT_DIR=/usr/local/opt/openssl

    script:
    - cmake -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DOPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include/ -DDEBUG=OFF . && make && cd www && npm install && npm build

before_deploy:
  - tar czf micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz micasa lib/open-zwave/config www/index.html www/css www/app
  - shasum -a 256 micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz > micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz.sha256sum
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KQEU8acf8S/tEsiyUpjJZdL/4ug4fBJt3imCo4BKIRe/maxULEbldyFljj5FRaIY+dAg0J86V+8o2sWrmoMrH/SKam7l6Q8beCOPQRyVGbix6Yeyzu1zVYJ7mT92FApDplVhtKYK2JmVoHp2HqA0s1SNRPDfdgCeoViNkMKbscLmDSnCVnddWPRo/V0z6JU0sL+9I3lEkA3hzN/OBBgJRuM6IMlBRzT71TeG/Qu8yAUQGlts9FzVUl4VpJ/ryvPCplu+57TRqb4og4mZljem4C95+qZhQDX/qNDq/cHAdzWCe9XUgyrwRbIsqGf6pu2Bhdk4L5mVT45DWWLWaEPg6/po6IzC6uD/Qrcth0cCwWvqzHVf/3BORKSEUT3+Ayc6u2uPbUGBZrxwERO3Ihf8Mxp1qaylgpWZqy7kH/2pPWRuwiKkbNTAUOodNenvigY60HoevkDu3bc7MbRGlL3cOtYnRP9J9J+J8sTVk1ouBptd1otKGqzUgJeUrd+qMXPGI/lqQcBEhiUoIEfg0yTMsdQPqo2endxN0M1FwySVRAWyrVA4Z/O4Efm8F42Z7KqFyRsQhSapjUsWTrMc4GCn45j8xGElpZkNqG5STY2/ZJHMfBS68LV6B+cqPDwcC2iaUnlzkcOUymL7Q0AWOBPAfaXh6tBW/YfiZWBqEqieFaI=
  file:
    - "micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz"
    - "micasa_${TRAVIS_OS_NAME}_${TARGET_ARCHITECTURE}.tgz.sha256sum"
  on:
    repo: fellownet/micasa
    tags: true
