language: cpp

matrix:
  # Linux x86_64
  include:
  - os: linux

    env:
    - TARGET_ARCHITECTURE=x86_64
    - TRAVIS_NODE_VERSION="7"

    compiler:
    - gcc

    install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - sudo apt-get install -y nodejs

    addons:
        apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - gcc-4.9
            - g++-4.9
            - cmake
            - libsqlite3-dev
            - curl
            - libcurl4-openssl-dev
            - libssl-dev
            - libudev-dev
            - git

    script:
    - cmake -DDEBUG=OFF . && make && cd www && npm install && npm build

  # OSX
  - os: osx
    osx_image: xcode6.2

    env:
    - TARGET_ARCHITECTURE=x86_64
    - TRAVIS_NODE_VERSION="7"

    compiler:
    - gcc

    install:
      - brew install libusb
      - brew install libusb-compat
      - brew install openssl
      - brew link openssl --force
      - brew install node
      - export OPENSSL_ROOT_DIR=/usr/local/opt/openssl

    script:
    - cmake -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DOPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include/ -DDEBUG=OFF . && make && cd www && npm install && npm build
