language: cpp

os: linux

compiler:
- gcc

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - g++-4.9
        - cmake
        - libsqlite3-dev
        - curl
        - libcurl4-openssl-dev
        - libssl-dev
        - libudev-dev
        - git

script:
- cmake -DDEBUG=OFF . && make
